using OrderingSystem.Domain.Enums;

namespace OrderingSystem.Application.Features.Orders;

/// <summary>
/// Placing the basket as an order.
/// </summary>
/// <param name="ExpectedTotalUsd">
/// The total the customer was shown, sent back so it can be checked — not so it can be used.
/// <para>
/// The server prices the order itself and always wins. This is the customer saying "I agreed to
/// $23.75"; if the menu moved since the quote, the two disagree and the checkout stops rather
/// than charging a number nobody consented to. Honouring the client's figure instead would let a
/// stale tab set the price.
/// </para>
/// </param>
/// <param name="IdempotencyKey">
/// One value per checkout attempt, generated by the client.
/// <para>
/// A customer on a bad connection taps Place Order, sees nothing happen and taps again. Without
/// this they are charged twice and a kitchen cooks the same food twice. With it the second
/// request finds the first order and returns it, which is what the unique index on the column
/// exists to make possible.
/// </para>
/// </param>
public sealed record CheckoutRequest(
    FulfillmentType Fulfillment,
    Guid? AddressId,
    PaymentMethod PaymentMethod,
    string? CustomerNote,
    decimal ExpectedTotalUsd,
    Guid IdempotencyKey);

public sealed record PlacedOrderResponse(
    Guid Id,
    string OrderNumber,
    OrderStatus Status,
    FulfillmentType Fulfillment,
    decimal SubtotalUsd,
    decimal DeliveryFeeUsd,
    decimal TotalUsd,
    decimal? TotalLbp,
    int PromisedMinutesMin,
    int PromisedMinutesMax,
    PaymentMethod PaymentMethod,
    PaymentStatus PaymentStatus,
    DateTimeOffset PlacedAt);
